### ISSUE TITLE
BaseView 질문

### ISSUE THREAD

**Issue by hongbeomi** [JSpiner/android-starter-kit#1]
안녕하세요! @JSpiner 님🙂

라이브러리를 살펴보던 도중 궁금한 점이 생겨 이슈를 남겼습니다.
`BaseView`클래스는 `FrameLayout`을 상속받도록 작성하셨는데 다른 뷰그룹도 많이 존재하는데 그 중
`FrameLayout`을 상속받는 이유를 알 수 있을까요?

**Comment by JSpiner** [comment]
안녕하세요?

1. 
`BaseView`인데 ViewGroup(기반의 FrameLayout)을 사용하는 이유는 
DataBindingUtil로 inflate된 뷰를 attach해서 사용하기 위함입니다.
(어쩌면 `BaseViewGroup`이 더 적절했을 수도 있겠네요 🤔 )

2.
DataBindingUtil로 inflate시킨 1개의 뷰를 attach 시키는 형태라
hierarchy 관련 속성이 필요가 없었습니다. 
FrameLayout은 hierarchy 속성이 없고 가볍기 때문에 사용하였습니다.

3.
관심 가져주셔서 감사합니다. 🙇 
`BaseView`는 deprecated될 예정입니다.
compose를 직접 사용하거나 래핑된 형태로 바뀔거에요

**Comment by hongbeomi** [comment]
그렇군요 ㅎㅎ 상세한 답변 감사드립니다 🙇
